// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.roo.addon.metadatable.domain;

import com.github.lbroudoux.roo.addon.metadatable.domain.Tweet;
import java.util.List;
import java.util.Map;
import javax.persistence.ElementCollection;

privileged aspect Tweet_Roo_Metadatable {
    
    @ElementCollection
    private Map<String, String> Tweet.metadatas = new java.util.HashMap<String, String>();
    
    public Map<String, String> Tweet.getMetadatas() {
        return this.metadatas;
    }
    
    public void Tweet.addMetadata(String key, String value) {
        this.metadatas.put(key, value);
    }
    
    public static List<Tweet> Tweet.findAllTweetsWithMetadata(String key) {
        return entityManager().createQuery("SELECT o FROM Tweet o, IN (o.metadatas) value WHERE index(value)='" + key + "'").getResultList();
        //return entityManager().createQuery("SELECT o FROM Tweet o WHERE key='" + key + "' IN (o.metadatas)").getResultList();
    }
    
    public static List<Tweet> Tweet.findAllTweetsWithMetadataValue(String key, String value) {
        return entityManager().createQuery("SELECT o FROM Tweet o, IN (o.metadatas) value WHERE value='" + value + "' AND index(value) = '" + key + "'").getResultList();
    }
    
}
